"""Provider-neutral deterministic market-data foundation contracts."""

from ai_platform.market_data.contracts import (
    AvailabilityTimestampKind,
    CaptureManifest,
    CaptureRequest,
    ChannelFamily,
    CompressionPolicy,
    EventType,
    Exchange,
    FrozenJsonObject,
    GapMarker,
    GapReason,
    InstrumentSnapshot,
    MarketType,
    OutputImmutabilityState,
    RawMarketEventEnvelope,
    SegmentManifest,
    UniverseDecision,
    UniverseSnapshot,
    assert_order_book_reconstructible,
    canonical_instrument_id,
    canonical_sha256,
    load_and_validate_contract_json,
    raw_payload_sha256,
    refuse_trading_credentials,
    validate_contract_payload,
)
from ai_platform.market_data.source_catalog import SourceCatalog, load_source_catalog
from ai_platform.market_data.universe import (
    DEFAULT_POLICIES,
    MetricSnapshot,
    MissingMetricBehavior,
    SourceMode,
    UniverseSelectionPolicy,
    select_universe,
)

__all__ = [
    "AvailabilityTimestampKind",
    "CaptureManifest",
    "CaptureRequest",
    "ChannelFamily",
    "CompressionPolicy",
    "DEFAULT_POLICIES",
    "EventType",
    "Exchange",
    "FrozenJsonObject",
    "GapMarker",
    "GapReason",
    "InstrumentSnapshot",
    "MarketType",
    "MetricSnapshot",
    "MissingMetricBehavior",
    "OutputImmutabilityState",
    "RawMarketEventEnvelope",
    "SegmentManifest",
    "SourceCatalog",
    "SourceMode",
    "UniverseDecision",
    "UniverseSelectionPolicy",
    "UniverseSnapshot",
    "assert_order_book_reconstructible",
    "canonical_instrument_id",
    "canonical_sha256",
    "load_and_validate_contract_json",
    "load_source_catalog",
    "raw_payload_sha256",
    "refuse_trading_credentials",
    "select_universe",
    "validate_contract_payload",
]
