from pathlib import Path
p=Path('ai_platform/portal/execution/host_isolation.py')
s=p.read_text()
a=s.index('    def cleanup_network')
b=s.index('    def _storage_capability',a)
new='''    def cleanup_network(self, network_name: str, runtime_id: str) -> None:\n        table = self._table_name(network_name)\n        expected = self._network_ids.get(runtime_id)\n        current = self._runner.run(\n            ("docker", "network", "inspect", "--format", "{{json .}}", network_name)\n        )\n        present = False\n        if current.returncode == 0:\n            present = True\n            network = self._parse_network_ownership(current)\n            if expected is None:\n                raise RuntimeDriverError(\n                    "GENERATION_OWNERSHIP_CONFLICT",\n                    "immutable network identity is unavailable; refusing name-based cleanup",\n                )\n            self._require_network_identity(network, runtime_id, expected)\n        elif not self._cleanup_target_absent(current):\n            raise RuntimeDriverError(\n                "GENERATION_OWNERSHIP_CONFLICT",\n                current.stderr.strip() or "generation network ownership evidence is unavailable",\n            )\n        if expected is None:\n            return\n        if not present:\n            immutable = self._runner.run(\n                ("docker", "network", "inspect", "--format", "{{json .}}", expected)\n            )\n            if immutable.returncode == 0:\n                network = self._parse_network_ownership(immutable)\n                self._require_network_identity(network, runtime_id, expected)\n                present = True\n            elif not self._cleanup_target_absent(immutable):\n                raise RuntimeDriverError(\n                    "GENERATION_OWNERSHIP_CONFLICT",\n                    immutable.stderr.strip() or "immutable generation network evidence is unavailable",\n                )\n        if present:\n            removed = self._runner.run(("docker", "network", "rm", expected))\n            if removed.returncode != 0 and not self._cleanup_target_absent(removed):\n                raise RuntimeDriverError(\n                    "HOST_NETWORK_CLEANUP_FAILED",\n                    "generation network cleanup was incomplete; retaining nftables policy: "\n                    + (removed.stderr.strip() or "Docker network cleanup failed"),\n                )\n        nft_result = self._runner.run(("nft", "delete", "table", "inet", table))\n        if nft_result.returncode != 0 and not self._cleanup_target_absent(nft_result):\n            raise RuntimeDriverError(\n                "HOST_NETWORK_CLEANUP_FAILED",\n                "generation network was removed but nftables table cleanup failed: "\n                + (nft_result.stderr.strip() or "nftables table cleanup failed"),\n            )\n        self._network_ids.pop(runtime_id, None)\n\n'''
s=s[:a]+new+s[b:]
marker='    def _network_info(self, network_name: str) -> dict[str, Any]:\n'
assert s.count(marker)==1
helpers='''    def _captured_network_id(self, runtime_id: str) -> str:\n        network_id = self._network_ids.get(runtime_id)\n        if not network_id:\n            raise RuntimeDriverError(\n                "GENERATION_OWNERSHIP_CONFLICT",\n                "immutable network identity is unavailable for the requested generation",\n            )\n        return network_id\n\n    @staticmethod\n    def _parse_network_ownership(result: CommandResult) -> dict[str, Any]:\n        try:\n            payload = json.loads(result.stdout)\n        except json.JSONDecodeError as exc:\n            raise RuntimeDriverError(\n                "GENERATION_OWNERSHIP_CONFLICT",\n                "generation network ownership evidence is invalid",\n            ) from exc\n        if not isinstance(payload, dict):\n            raise RuntimeDriverError(\n                "GENERATION_OWNERSHIP_CONFLICT",\n                "generation network ownership evidence has an unexpected shape",\n            )\n        return payload\n\n    @staticmethod\n    def _require_network_identity(\n        network: dict[str, Any], runtime_id: str, expected: str\n    ) -> None:\n        network_id = network.get("Id")\n        labels = network.get("Labels")\n        if (\n            not isinstance(network_id, str)\n            or not network_id\n            or not isinstance(labels, dict)\n            or labels.get("ai.portal.runtime_id") != runtime_id\n            or network_id != expected\n        ):\n            raise RuntimeDriverError(\n                "GENERATION_OWNERSHIP_CONFLICT",\n                "generation network immutable identity does not match runtime ownership",\n            )\n\n    def _owned_network_info(self, network_name: str, runtime_id: str) -> dict[str, Any]:\n        expected = self._captured_network_id(runtime_id)\n        network = self._network_info(network_name)\n        self._require_network_identity(network, runtime_id, expected)\n        return network\n\n'''
s=s.replace(marker,helpers+marker,1)
p.write_text(s)
