from pathlib import Path
p=Path('ai_platform/portal/execution/driver.py')
s=p.read_text()
a=s.index('    def inspect(')
b=s.index('    def _application_probe',a)
new='''    def inspect(self, runtime_id: str) -> DriverRuntimeState:\n        container_id = self._owned_container_id(runtime_id)\n        if container_id is None:\n            return DriverRuntimeState.MISSING\n        result = self._runner.run(("docker", "inspect", "--format", "{{.State.Status}}", container_id))\n        if result.returncode != 0:\n            if "no such object" in result.stderr.lower():\n                return DriverRuntimeState.MISSING\n            raise RuntimeDriverError(\n                "DOCKER_INSPECT_FAILED",\n                result.stderr.strip() or "docker inspect failed",\n            )\n        state = result.stdout.strip().lower()\n        if state == "running":\n            gate = self._runner.run(("docker", "exec", container_id, "test", "-f", self._RELEASE_FILE))\n            if gate.returncode == 0:\n                if self._application_probe(runtime_id, container_id):\n                    return DriverRuntimeState.RUNNING\n                return DriverRuntimeState.STARTING\n            if gate.returncode == 1:\n                return DriverRuntimeState.CREATED\n            raise RuntimeDriverError(\n                "ISOLATION_ATTESTATION_FAILED",\n                gate.stderr.strip() or "quarantine state is unreadable",\n            )\n        states = {\n            "created": DriverRuntimeState.CREATED,\n            "restarting": DriverRuntimeState.STARTING,\n            "paused": DriverRuntimeState.PAUSED,\n            "exited": DriverRuntimeState.STOPPED,\n            "dead": DriverRuntimeState.STOPPED,\n        }\n        try:\n            return states[state]\n        except KeyError as exc:\n            raise RuntimeDriverError(\n                "DOCKER_STATE_UNKNOWN",\n                f"unsupported docker runtime state: {state or '<empty>'}",\n            ) from exc\n\n'''
s=s[:a]+new+s[b:]
s=s.replace('    def _application_probe(self, runtime_id: str) -> bool:\n','    def _application_probe(self, runtime_id: str, container_id: str) -> bool:\n',1)
old='''                "docker",\n                "exec",\n                runtime_id,\n                "/bin/sh",\n                "-ec",\n                script,\n                "portal-readiness",\n'''
new2='''                "docker",\n                "exec",\n                container_id,\n                "/bin/sh",\n                "-ec",\n                script,\n                "portal-readiness",\n'''
assert s.count(old)==1
s=s.replace(old,new2,1)
p.write_text(s)
