from pathlib import Path
p=Path('ai_platform/portal/execution/driver.py')
s=p.read_text()
def r(a,b):
 global s
 assert s.count(a)==1,(a[:60],s.count(a)); s=s.replace(a,b,1)
r('''            if not created_container_id:\n                raise RuntimeDriverError(\n                    "DOCKER_CREATE_FAILED",\n                    "Docker create did not return an immutable container identity",\n                )\n            self._attest_structural(spec, plan, network)\n            self._require_success(("docker", "start", spec.runtime_id), "DOCKER_START_FAILED")\n''','''            if not created_container_id:\n                raise RuntimeDriverError(\n                    "DOCKER_CREATE_FAILED",\n                    "Docker create did not return an immutable container identity",\n                )\n            self._container_ids[spec.runtime_id] = created_container_id\n            self._attest_structural(spec, plan, network)\n            self._require_success(("docker", "start", created_container_id), "DOCKER_START_FAILED")\n''')
r('''            container_id = self._owned_container_id(runtime_id)\n            if container_id is None:\n                raise RuntimeDriverError("RUNTIME_MISSING", "runtime container does not exist")\n            self._require_success(("docker", "pause", container_id), "DOCKER_PAUSE_FAILED")\n''','''            container_id = self._captured_container_id(runtime_id)\n            self._require_success(("docker", "pause", container_id), "DOCKER_PAUSE_FAILED")\n''')
r('''            container_id = self._owned_container_id(runtime_id)\n            if container_id is None:\n                raise RuntimeDriverError("RUNTIME_MISSING", "runtime container does not exist")\n            self._require_success(("docker", "stop", container_id), "DOCKER_STOP_FAILED")\n''','''            container_id = self._captured_container_id(runtime_id)\n            self._require_success(("docker", "stop", container_id), "DOCKER_STOP_FAILED")\n''')
r('''        if current is not DriverRuntimeState.MISSING:\n            container_id = self._owned_container_id(runtime_id)\n            if container_id is not None:\n                self._require_success(("docker", "rm", "-f", container_id), "DOCKER_REMOVE_FAILED")\n''','''        if current is not DriverRuntimeState.MISSING:\n            container_id = self._captured_container_id(runtime_id)\n            self._require_success(("docker", "rm", "-f", container_id), "DOCKER_REMOVE_FAILED")\n''')
r('        info = self._inspect_json(spec.runtime_id)\n','        info = self._inspect_json(self._captured_container_id(spec.runtime_id))\n')
r('''    def _release(self, runtime_id: str) -> None:\n        self._require_success(\n            ("docker", "exec", runtime_id, "/bin/sh", "-ec", self._RELEASE),\n''','''    def _release(self, runtime_id: str) -> None:\n        container_id = self._captured_container_id(runtime_id)\n        self._require_success(\n            ("docker", "exec", container_id, "/bin/sh", "-ec", self._RELEASE),\n''')
p.write_text(s)
